# menu
menu:
  Home: .
  Archives: archives  # 归档
  Categories: categories  # 分类
  Tags: tags  # 标签
  Repository: repository  # github repositories
  # Books: books  # 豆瓣书单
  Links: links  # 友链
  About: about  # 关于

# Enable/Disable menu icons
menu_icons:
  enable: true  # 是否启用导航菜单图标
  home: icon-home-fill
  archives: icon-archives-fill
  categories: icon-folder
  tags: icon-tags
  repository: icon-project
  books: icon-book-fill
  links: icon-friendship
  about: icon-cup-fill

# rss
rss: /atom.xml

# Site
site:
  logo:
    enabled: false
    width: 400
    height: 400
    url: ../images/logo.png
  title: 非典型性程序员 # 页面title
  favicon: /favicon.png
  board: <p>个人站正式上线, 不断优化改进中!</p> # 站点公告
  copyright: true # 底部版权信息

# config
config:
  skin: # 主题颜色 theme-black theme-blue theme-green theme-purple
  layout: main-center # 布局方式 main-left main-center main-right
  toc: true # 是否开启文章章节目录导航
  menu_highlight: true # 是否开启当前菜单高亮显示
  thumbnail: false # 右下角最新文章是否展示缩略图, options: true, false
  excerpt_link: Read More

# 分页情况
pagination:
  number: true
  prev: 
    alwayShow: true
  next:
    alwayShow: true

# 侧边栏
sidebar: right
# 侧边栏启用哪些模块
widgets:
  - board  
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive  

# 归档列表的展示方式
archive_type: 'monthly' # 归档方式:  yearly | monthly
show_count: true # 显示每个归档的文章总数

# Fancybox
# 图集功能
fancybox: true

# Search
search:
  insight: true # you need to install `hexo-generator-json-content` before using Insight Search
  baidu: false # you need to disable other search engines to use Baidu search

# Donate
donate:
  enable: true
  # 微信打赏
  wechatpay:
    qrcode: images/donate/wechatpayimg.png
    title: 微信支付
  # 支付宝打赏
  alipay: 
    qrcode: images/donate/alipayimg.png 
    title: 支付宝

# Share
# weibo,qq,qzone,wechat,tencent,douban,diandian,facebook,twitter,google,linkedin
share:
  enable: true  # 是否启用分享
  sites: weibo,qq,wechat,facebook,twitter  # PC端显示的分享图标
  mobile_sites: weibo,qq,qzone  # 移动端显示的分享图标

# Github
# 展示geihub项目数据
github: 
  username: caoruiy  # github用户名

# Comment
# Gitment
# Introduction: https://imsun.net/posts/gitment-introduction/
comment:
  type: valine  # 启用哪种评论系统
  disqus:  # enter disqus shortname here
  youyan: 
    uid: 1783844 # enter youyan uid 
  livere:
    uid: # enter youyan uid 
  gitment:
    githubID: 
    repo: 
    ClientID: 
    ClientSecret: 
    lazy: false
  gitalk: # gitalk. https://gitalk.github.io/
    owner:  #必须. GitHub repository 所有者，可以是个人或者组织。
    admin:  #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
    repo:  #必须. GitHub repository.
    ClientID:  #必须. GitHub Application Client ID.
    ClientSecret:  #必须. GitHub Application Client Secret.
  valine: # Valine. https://valine.js.org
    appid: dR1qyrvU6qgrRgNGXJRybXuc-gzGzoHsz # your leancloud application appid
    appkey: 5tjvd45ScSphfpjfPI1pNqFJ # your leancloud application appkey
    notify: true # mail notifier , https://github.com/xCss/Valine/wiki
    verify: false # Verification code
    placeholder: 说点什么... # comment box placeholder
    avatar: monsterid # 头像展示方式
    meta: nick,mail,link # 自定义评论信息
    pageSize: 10 # 评论列表分页
    lang: zh-cn, # 多语言支持 zh-cn | en
    visitor: true # 文章阅读量统计:  https://valine.js.org/visitor.html

# douban 豆瓣书单
# Api：
  # https://developers.douban.com/wiki/?title=book_v2 图书
  # https://developers.douban.com/wiki/?title=movie_v2 电影
# books：  
  # https://api.douban.com/v2/book/user/:name/collections?start=0&count=100 个人书单列表
# movies: 
  # https://api.douban.com/v2/movie/in_theaters 正在上映的电影
  # https://api.douban.com/v2/movie/coming_soon 即将上映的电影
  # https://api.douban.com/v2/movie/subject/:id 单个电影信息
  # https://api.douban.com/v2/movie/search?q={text} 电影搜索
douban:
  user: 196924043 # 豆瓣用户名
  start: 0 # 从哪一条记录开始
  count: 100 # 获取豆瓣书单数据条数
  
# PV
pv:
  busuanzi:
    enable: false  # 不蒜子统计
  leancloud:
    enable: false  # leancloud统计
    appid: ItG3aLpSkKnK4EsTCGOkRj9T-gzGzoHsz # your leancloud application appid
    appkey: C5bqVJG6bnWkWiOIV0V38h37
        
# wordcount
postCount:
  enable: true
  wordcount: true  # 文章字数统计
  min2read: true  # 阅读时长预计 

# Plugins
plugins:
  google_analytics: # enter the tracking ID for your Google Analytics
  google_site_verification: # enter Google site verification code
  baidu_analytics: # enter Baidu Analytics hash key
  tencent_analytics: 
  
# Miscellaneous
twitter:
google_plus:
fb_admins:
fb_app_id:  
  
# profile
profile:
  enabled: true # Whether to show profile bar
  avatar: images/avatar.jpeg
  gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: 曹一山
  author_title: Web Developer & Designer
  author_description: 一个Web开发者, 热爱生活, 崇尚技术。 # 详情页文尾显示
  location: 苏州, 中国
  follow: https://github.com/caoruiy
  # Social Links
  # 页面左下角链接, 可以自定义名称
  social:
    links:
      github: https://github.com/caoruiy
      weibo: http://weibo.com/NollyUp
      # twitter: /
      # facebook: /
      # dribbble: /
      # behance: /
      rss: atom.xml
    link_tooltip: true # enable the social link tooltip, options: true, false
  # My Skills 
  skills:
    HTML+CSS: ★★★★☆
    Javascript: ★★★☆☆
    Git: ★★★☆☆
    ES6: ★★★☆☆
    php: ★★★☆☆
    Webpack: ★★☆☆☆
    Gulp: ★★☆☆☆
    Linux: ★☆☆☆☆
  # My Personal Links
  links:
    Github: https://github.com/caoruiy
    Blog: https://blog.plcent.com
    微博: http://weibo.com/NollyUp
  # My Personal Labels
  labels:
    - 前端
    - 前端开发
    - 前端重构
    - Web前端
    - Node
    - Vue
    - 网页重构
    - Python
  # My Personal Works
  # 个人作品
  works:
    江苏大学慕课平台:
      link: http://mooc.coinboy.net/
      date: 2017
  # My Personal Projects
  projects:
    # cofess/gulp-startpro: https://github.com/cofess/gulp-startpro
    # cofess/hexo-theme-pure: https://github.com/cofess/hexo-theme-pure