# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 非典型性程序员
subtitle: -------------------
description: 曹一山的个人博客, 崇尚技术, 前端开发一枚,
keywords: 非典型性程序员, 博客
author: 曹一山
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: 'https://blog.plcent.com/'
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: false #禁用永久链接后的index.html

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
# 跳过指定文件的渲染。匹配到的文件将会被不做改动地复制到 public 目录中。您可使用 glob 表达式来匹配路径。
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
# 新建文章时新建asset文件夹
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: pure

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  # type: git
  # repo: git@github.com:caoruiy/blog.plcent.com.git
  # branch: hexo
  type: git
  repo: git@134.175.52.144:/data/git/blog.plcent.com
  branch: master


# 自动生成分类
category_generator:
  per_page: 20
  order_by: -date

# 自动生成Tag
tag_generator:
  per_page: 20
  order_by: -date

# 文章加密
encrypt: # hexo-blog-encrypt
  abstract: 这是一篇私密文章！
  message: 继续阅读请输入密码！
  # tags:
  # - {name: tagName, password: 密码A}
  # - {name: tagName, password: 密码B}
  wrong_pass_message: 密码错误，请重试。
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容.